function New_C=fun_update2D(C,u_vel_t,v_vel_t,Dt,Dspace,Source)
% fun_rule returns a New value field based on Cellular automata local rule
% Input C is the value field to be calculated
% Input parameter is an object contains all neede parameters.

%% Parameter initilization
[IX,IY]=size(u_vel_t);
New_C=zeros(IX,IY);

ii=2:IX-1;
jj=2:IY-1;


U_e_tp=-u_vel_t;
U_n_tp=-v_vel_t;
U_w_tp=u_vel_t;
U_s_tp=v_vel_t;

U_ne_tp=-u_vel_t*cos(4/pi)-v_vel_t*cos(4/pi);
U_nw_tp=u_vel_t*cos(4/pi)-v_vel_t*cos(4/pi);
U_sw_tp=u_vel_t*cos(4/pi)+v_vel_t*cos(4/pi);
U_se_tp=-u_vel_t*cos(4/pi)+v_vel_t*cos(4/pi);

U_e=1/2*(abs(U_e_tp)+U_e_tp);
U_n=1/2*(abs(U_n_tp)+U_n_tp);
U_w=1/2*(abs(U_w_tp)+U_w_tp);
U_s=1/2*(abs(U_s_tp)+U_s_tp);

U_ne=1/2*(abs(U_ne_tp)+U_ne_tp);
U_nw=1/2*(abs(U_nw_tp)+U_nw_tp);
U_sw=1/2*(abs(U_sw_tp)+U_sw_tp);
U_se=1/2*(abs(U_se_tp)+U_se_tp);

clear U_e_tp U_n_tp U_w_tp U_s_tp U_ne_tp U_nw_tp U_se_tp U_sw_tp


wa=0.8;
wb=0.5;

diffusion_flag=1;   % 0 -> no dispersion

% dispersion coefficient

Kx=1e-3;  % horizental dispersion coefficient on x axis
Ky=1e-3;
Kxy=1e-3;

% deposition and reaction
% delta=zeros(IX,IY);   % deposition
% lambda=zeros(IX,IY);  % reaction

%% Local configuration
%
%   (NW)       (N)       (NE)
%   i-1,j+1   i,j+1     i+1,j+1
%
%    (W)       (O)       (E)
%   i-1,j      i,j      i+1,j
%
%   (SW)       (S)       (SE)
%   i-1,j-1   i,j-1     i+1,j-1

%% Function body
if diffusion_flag == 0
% Local update in main body
New_C(ii,jj)=C(ii,jj)+...
    wa*Dt/Dspace*(...
    U_n(ii,jj).*(C(ii,jj+1)-C(ii,jj))+...
    U_s(ii,jj).*(C(ii,jj-1)-C(ii,jj))+...
    U_e(ii,jj).*(C(ii+1,jj)-C(ii,jj))+...
    U_w(ii,jj).*(C(ii-1,jj)-C(ii,jj)) )+...
    wb*Dt/Dspace/sqrt(2)*( ...
    U_ne(ii,jj).*(C(ii+1,jj+1)-C(ii,jj))+...
    U_nw(ii,jj).*(C(ii-1,jj+1)-C(ii,jj))+...
    U_sw(ii,jj).*(C(ii-1,jj-1)-C(ii,jj))+...
    U_se(ii,jj).*(C(ii+1,jj-1)-C(ii,jj))  )+...
    Source(ii,jj)*Dt;

%%% Boundary Conditions
% South Boundary
New_C(ii,1)=C(ii,1)+...
    wa*Dt/Dspace*(...
    U_n(ii,1).*(C(ii,2)-C(ii,1))+...
    U_e(ii,1).*(C(ii+1,1)-C(ii,1))+...
    U_w(ii,1).*(C(ii-1,1)-C(ii,1))  )+...
    wb*Dt/Dspace/sqrt(2)*(...
    U_ne(ii,1).*(C(ii+1,2)-C(ii,1))+...
    U_nw(ii,1).*(C(ii-1,2)-C(ii,1))  )+...
    Source(ii,1)*Dt;

% North Boundary
New_C(ii,IY)=C(ii,IY)+...
    wa*Dt/Dspace*(...
    U_s(ii,IY).*(C(ii,IY-1)-C(ii,IY))+...
    U_e(ii,IY).*(C(ii+1,IY)-C(ii,IY))+...
    U_w(ii,IY).*(C(ii-1,IY)-C(ii,IY))  )+...
    wb*Dt/Dspace/sqrt(2)*(...
    U_se(ii,IY).*(C(ii+1,IY-1)-C(ii,IY))+...
    U_sw(ii,IY).*(C(ii-1,IY-1)-C(ii,IY))  )+...
    Source(ii,IY)*Dt;

% East Boundary
New_C(IX,jj)=C(IX,jj)+...*
    wa*Dt/Dspace.*(...
    U_s(IX,jj).*(C(IX,jj-1)-C(IX,jj))+...
    U_w(IX,jj).*(C(IX-1,jj)-C(IX,jj))+...
    U_n(IX,jj).*(C(IX,jj+1)-C(IX,jj))  )+...
    wb*Dt/Dspace/sqrt(2)*(...
    U_nw(IX,jj).*(C(IX-1,jj+1)-C(IX,jj))+...
    U_sw(IX,jj).*(C(IX-1,jj-1)-C(IX,jj))  )+...
    Source(IX,jj)*Dt;

% West Boundary
New_C(1,jj)=C(1,jj)+...
    wa*Dt/Dspace.*(...
    U_s(1,jj).*(C(1,jj-1)-C(1,jj))+...
    U_e(1,jj).*(C(2,jj)-C(1,jj))+...
    U_n(1,jj).*(C(1,jj+1)-C(1,jj))  )+...
    wb*Dt/Dspace/sqrt(2)*(...
    U_ne(1,jj).*(C(2,jj+1)-C(1,jj))+...
    U_se(1,jj).*(C(2,jj-1)-C(1,jj))  )+...
    Source(1,jj)*Dt;

% SW Corner  (1,1)
New_C(1,1)=C(1,1)+...
    wa*Dt/Dspace.*(...
    U_n(1,1).*(C(1,2)-C(1,1))+...
    U_e(1,1).*(C(2,1)-C(1,1))  )+...
    wb*Dt/Dspace/sqrt(2)*( ...
    U_ne(1,1).*(C(2,2)-C(1,1))  )+...
    Source(1,1)*Dt;

% NE Corner (IX,IY)
New_C(IX,IY)=C(IX,IY)+...
    wa*Dt/Dspace.*(...
    U_s(IX,IY).*(C(IX,IY-1)-C(IX,IY))+...
    U_w(IX,IY).*(C(IX-1,IY)-C(IX,IY))  )+...
    wb*Dt/Dspace/sqrt(2)*( ...
    U_sw(IX,IY).*(C(IX-1,IY-1)-C(IX,IY))  )+...
    Source(IX,IY)*Dt;

% NW Corner  (1,IY)
New_C(1,IY)=C(1,IY)+...
    wa*Dt/Dspace.*(...
    U_s(1,IY).*(C(1,IY-1)-C(1,IY))+...
    U_e(1,IY).*(C(2,IY)-C(1,IY))  )+...
    wb*Dt/Dspace/sqrt(2)*( ...
    U_se(1,IY).*(C(2,IY-1)-C(1,IY))  )+...
    Source(1,IY)*Dt;

% SE Corner  (IX,1)
New_C(IX,1)=C(IX,1)+...
    wa*Dt/Dspace.*(...
    U_n(IX,1).*(C(IX,2)-C(IX,1))+...
    U_w(IX,1).*(C(IX-1,1)-C(IX,1))  )+...
    wb*Dt/Dspace/sqrt(2)*( ...
    U_nw(IX,1).*(C(IX-1,2)-C(IX,1))  )+...
    Source(IX,1)*Dt;


%% Diffusion considered
elseif diffusion_flag == 1
    
% Local update in main body
New_C(ii,jj)=C(ii,jj)+...
    Kx*Dt/Dspace^2*(C(ii+1,jj)+C(ii-1,jj)-2*C(ii,jj))+...
    Ky*Dt/Dspace^2*(C(ii,jj+1)+C(ii,jj-1)-2*C(ii,jj))+...
    Kxy*Dt/Dspace^2/2*(C(ii+1,jj-1)+C(ii-1,jj+1)-2*C(ii,jj))+...
    Kxy*Dt/Dspace^2/2*(C(ii-1,jj-1)+C(ii+1,jj+1)-2*C(ii,jj))+...
    wa*Dt/Dspace*(...
    U_n(ii,jj).*(C(ii,jj+1)-C(ii,jj))+...
    U_s(ii,jj).*(C(ii,jj-1)-C(ii,jj))+...
    U_e(ii,jj).*(C(ii+1,jj)-C(ii,jj))+...
    U_w(ii,jj).*(C(ii-1,jj)-C(ii,jj)) )+...
    wb*Dt/Dspace/sqrt(2)*( ...
    U_ne(ii,jj).*(C(ii+1,jj+1)-C(ii,jj))+...
    U_nw(ii,jj).*(C(ii-1,jj+1)-C(ii,jj))+...
    U_sw(ii,jj).*(C(ii-1,jj-1)-C(ii,jj))+...
    U_se(ii,jj).*(C(ii+1,jj-1)-C(ii,jj))  )+...
    Source(ii,jj)*Dt;

%%% Boundary Conditions
% South Boundary
New_C(ii,1)=C(ii,1)+...
    Kx*Dt/Dspace^2*(C(ii+1,1)+C(ii-1,1)-2*C(ii,1))+...
    Ky*Dt/Dspace^2*(C(ii,1+1)-2*C(ii,1))+...
    Kxy*Dt/Dspace^2/2*(C(ii-1,1+1)-2*C(ii,1))+...
    Kxy*Dt/Dspace^2/2*(C(ii+1,1+1)-2*C(ii,1))+...
    wa*Dt/Dspace*(...
    U_n(ii,1).*(C(ii,2)-C(ii,1))+...
    U_e(ii,1).*(C(ii+1,1)-C(ii,1))+...
    U_w(ii,1).*(C(ii-1,1)-C(ii,1))  )+...
    wb*Dt/Dspace/sqrt(2)*(...
    U_ne(ii,1).*(C(ii+1,2)-C(ii,1))+...
    U_nw(ii,1).*(C(ii-1,2)-C(ii,1))  )+...
    Source(ii,1)*Dt;

% North Boundary
New_C(ii,IY)=C(ii,IY)+...
    Kx*Dt/Dspace^2*(C(ii+1,IY)+C(ii-1,IY)-2*C(ii,IY))+...
    Ky*Dt/Dspace^2*(C(ii,IY-1)-2*C(ii,IY))+...
    Kxy*Dt/Dspace^2/2*(C(ii+1,IY-1)-2*C(ii,IY))+...
    Kxy*Dt/Dspace^2/2*(C(ii-1,IY-1)-2*C(ii,IY))+...
    wa*Dt/Dspace*(...
    U_s(ii,IY).*(C(ii,IY-1)-C(ii,IY))+...
    U_e(ii,IY).*(C(ii+1,IY)-C(ii,IY))+...
    U_w(ii,IY).*(C(ii-1,IY)-C(ii,IY))  )+...
    wb*Dt/Dspace/sqrt(2)*(...
    U_se(ii,IY).*(C(ii+1,IY-1)-C(ii,IY))+...
    U_sw(ii,IY).*(C(ii-1,IY-1)-C(ii,IY))  )+...
    Source(ii,IY)*Dt;

% East Boundary
New_C(IX,jj)=C(IX,jj)+...
    Kx*Dt/Dspace^2*(C(IX-1,jj)-2*C(IX,jj))+...
    Ky*Dt/Dspace^2*(C(IX,jj+1)+C(IX,jj-1)-2*C(IX,jj))+...
    Kxy*Dt/Dspace^2/2*(C(IX-1,jj+1)-2*C(IX,jj))+...
    Kxy*Dt/Dspace^2/2*(C(IX-1,jj-1)-2*C(IX,jj))+...
    wa*Dt/Dspace.*(...
    U_s(IX,jj).*(C(IX,jj-1)-C(IX,jj))+...
    U_w(IX,jj).*(C(IX-1,jj)-C(IX,jj))+...
    U_n(IX,jj).*(C(IX,jj+1)-C(IX,jj))  )+...
    wb*Dt/Dspace/sqrt(2)*(...
    U_nw(IX,jj).*(C(IX-1,jj+1)-C(IX,jj))+...
    U_sw(IX,jj).*(C(IX-1,jj-1)-C(IX,jj))  )+...
    Source(IX,jj)*Dt;

% West Boundary
New_C(1,jj)=C(1,jj)+...
    Kx*Dt/Dspace^2*(C(1+1,jj)-2*C(1,jj))+...
    Ky*Dt/Dspace^2*(C(1,jj+1)+C(1,jj-1)-2*C(1,jj))+...
    Kxy*Dt/Dspace^2/2*(C(1+1,jj-1)-2*C(1,jj))+...
    Kxy*Dt/Dspace^2/2*(C(1+1,jj+1)-2*C(1,jj))+...
    wa*Dt/Dspace.*(...
    U_s(1,jj).*(C(1,jj-1)-C(1,jj))+...
    U_e(1,jj).*(C(2,jj)-C(1,jj))+...
    U_n(1,jj).*(C(1,jj+1)-C(1,jj))  )+...
    wb*Dt/Dspace/sqrt(2)*(...
    U_ne(1,jj).*(C(2,jj+1)-C(1,jj))+...
    U_se(1,jj).*(C(2,jj-1)-C(1,jj))  )+...
    Source(1,jj)*Dt;

% SW Corner  (1,1)
New_C(1,1)=C(1,1)+...
    Kx*Dt/Dspace^2*(C(1+1,1)-2*C(1,1))+...
    Ky*Dt/Dspace^2*(C(1,1+1)-2*C(1,1))+...
    Kxy*Dt/Dspace^2/2*(C(1+1,1+1)-2*C(1,1))+...
    wa*Dt/Dspace.*(...
    U_n(1,1).*(C(1,2)-C(1,1))+...
    U_e(1,1).*(C(2,1)-C(1,1))  )+...
    wb*Dt/Dspace/sqrt(2)*( ...
    U_ne(1,1).*(C(2,2)-C(1,1))  )+...
    Source(1,1)*Dt;

% NE Corner (IX,IY)
New_C(IX,IY)=C(IX,IY)+...
    Kx*Dt/Dspace^2*(C(IX-1,IY)-2*C(IX,IY))+...
    Ky*Dt/Dspace^2*(C(IX,IY-1)-2*C(IX,IY))+...
    Kxy*Dt/Dspace^2/2*(C(IX-1,IY-1)-2*C(IX,IY))+...
    wa*Dt/Dspace.*(...
    U_s(IX,IY).*(C(IX,IY-1)-C(IX,IY))+...
    U_w(IX,IY).*(C(IX-1,IY)-C(IX,IY))  )+...
    wb*Dt/Dspace/sqrt(2)*( ...
    U_sw(IX,IY).*(C(IX-1,IY-1)-C(IX,IY))  )+...
    Source(IX,IY)*Dt;

% NW Corner  (1,IY)
New_C(1,IY)=C(1,IY)+...
    Kx*Dt/Dspace^2*(C(1+1,IY)-2*C(1,IY))+...
    Ky*Dt/Dspace^2*(C(1,IY-1)-2*C(1,IY))+...
    Kxy*Dt/Dspace^2/2*(C(1+1,IY-1)-2*C(1,IY))+...
    wa*Dt/Dspace.*(...
    U_s(1,IY).*(C(1,IY-1)-C(1,IY))+...
    U_e(1,IY).*(C(2,IY)-C(1,IY))  )+...
    wb*Dt/Dspace/sqrt(2)*( ...
    U_se(1,IY).*(C(2,IY-1)-C(1,IY))  )+...
    Source(1,IY)*Dt;

% SE Corner  (IX,1)
New_C(IX,1)=C(IX,1)+...
    Kx*Dt/Dspace^2*(C(IX-1,1)-2*C(IX,1))+...
    Ky*Dt/Dspace^2*(C(IX,1+1)-2*C(IX,1))+...
    Kxy*Dt/Dspace^2/2*(C(IX-1,1+1)-2*C(IX,1))+...
    wa*Dt/Dspace.*(...
    U_n(IX,1).*(C(IX,2)-C(IX,1))+...
    U_w(IX,1).*(C(IX-1,1)-C(IX,1))  )+...
    wb*Dt/Dspace/sqrt(2)*( ...
    U_nw(IX,1).*(C(IX-1,2)-C(IX,1))  )+...
    Source(IX,1)*Dt;    
    
    
    
end


